### ISSUE TITLE
General krb5 functions

### ISSUE THREAD

**Issue by tkdchen** [pythongssapi/python-gssapi#106]
My project [python-krbcontext](https://github.com/krbcontext/krbcontext/) relies on python-krbV heavily, and I've been told and suggest to choose python-gssapi, since it's been being developed actively, is compatible with Python 3, and a strong reason is gssapi can do everything krbV does. I have a quick look at gssapi and realize that it implements GSSAPI spec, whereas krbV handles `context`, `ccache`, `principal`, and `keytab` with lower level krb5 functions. So, I would like to ask if gssapi has equivalent functionalists, such as
- initialize `ccache` in either default or user-specified place
- read `keytab` from either default or user-specified place
- read credential cache info from a `ccache`, either the default or user-specified

My project actually doesn't require GSSAPI, because `krbcontext` works in the client side of a GSSAPI context, and it is designed to happen before client side code start to call gssapi APIs.

**Comment by DirectXMan12** [comment]
> - initialize ccache in either default or user-specified place

Can you be a bit more specific here?  Do you mean initialize an empty ccache?  Do you mean "perform the equivalent of a kinit"?

> - read keytab from either default or user-specified place
> - read credential cache info from a ccache, either the default or user-specified

When performing operations related to credentials, the GSSAPI functions will use the "default" ccache automatically (in MIT krb5, there are also environment variables that can be used to change this).  MIT krb5 supports multiple extensions to GSSAPI that allow you to work with specific ccaches and keytabs as well (see the `store` parameter on http://pythonhosted.org/gssapi/gssapi.html#gssapi.creds.Credentials.acquire or http://pythonhosted.org/gssapi/gssapi.raw.html#module-gssapi.raw.ext_cred_store, for example)

**Comment by frozencemetery** [comment]
> - initialize ccache in either default or user-specified place

To add on to what DirectXMan12 was saying, GSSAPI tries to be largely agnostic as to whether the credential storage it's using exists; that is, it will most often create it if it does not.  So a discrete "initialize" step is generally not needed and happens as part of credential acquisition.

**Comment by tkdchen** [comment]
@DirectXMan12 I can give some examples using ``krbV``

- Get and store credential using default ccache and keytab.
  - Credential will be stored in default ``/tmp/krb5cc_[uid]``
  - Using Kerberos default keytab ``/etc/krb5.keytab``

  ```
  context = krbV.default_context()
  ccache = context.default_ccache()
  keytab = context.default_keytab()
  pincipal = krbV.Principal('HTTP/hostname@REALM', context=context)
  ccache.init(principal)
  ccache.init_creds_keytab(principal=principal, keytab=keytab)
  ```

- Store credential into non-default ccache file.

  I can construct ccache object instead of calling ``default_ccache``.

  ```
  ccache = krbV.CCache('/tmp/krb5cc_myapp', context=context)
  ```

- Use an application-specific keytab.

  Similar with ``ccache``, I can construct keytab object instead of calling ``default_keytab``.

  ```
  keytab = krbV.Keytab('/etc/httpd/conf/httpd.keytab', context=context)
  ```

- Get credential information from a ccache

  ``CCache`` object provides a method ``get_credentials`` to get information from a ccache file, for example [line 68](https://github.com/krbcontext/krbcontext/blob/master/krbcontext/utils.py#L68).

All these functionalities depends on the krb5 C library functions, that is ``krb5_*``, rather than GSSAPI.

**Comment by tkdchen** [comment]
Generally, ``krbcontext`` works at lower level then GSSAPI in an application, as it only manipulates the credential in a ccache instead of the communication between application calling ``krbcontext`` and the service that application is attempting to talk with. The only remote service needed is the KDC if previous got credential has been expired. Based on my understand of GSSAPI, it's used in a different senario than ``krbcontext``. Please point out for me if something of GSSAPI I understand incorrectly. Thanks.

**Comment by simo5** [comment]
@tkdchen you should really describe what you need to do in the appication. GSSAPI is intentionally a more abstract API, but can generally do all that is needed.
If you use a modern MIT Kerberos distribution for example you can use the credentials store extensions to operate exactly on the ketabs and ccaches you want through the gss_aqcuire_cred_from/gss_store_creds_into() extension calls. These calls are available via python-gssapi if the underlying GSSAPI library supports them.

You can force the intialization of a ccache for example by Acquiring credentials specifying a name and a keytab, and then inspecting the returned Credentials object.
I am goign by memory but it would look something like:

Using default, name (as retrieved from the default keytab), default keytab and default ccache:
```
creds = gssapi.creds.Credentials(usage='initiate')
if creds.lifetime > 0:
    return true
```

Using default keytab and ccache, but choosing a specific principal name:
```
principal = gssapi.names.Name('HTTP/hostname@REALM',
                                                   gssapi.raw.NameType.kerberos_principal)
creds = gssapi.creds.Credentials(name=principal, usage='initiate')
```

Specifying a custom name, keytab and ccache:
```
store = {'ccache': 'FILE:/some/ccache/file', 'keytab':'/etc/some.keytab' }
principal = gssapi.names.Name('HTTP/hostname@REALM',
                                                   gssapi.raw.NameType.kerberos_principal)
creds = gssapi.creds.Credentials(name=principal, usage='initiate', store=store)
```

**Comment by tkdchen** [comment]
@simo5 Thanks for your examples, that's really helpful for me. Examples I gave above in [comment](https://github.com/pythongssapi/python-gssapi/issues/106#issuecomment-252791097) is what my project ``krbcontext`` does.

BTW, what other key-value pairs could be put in ``store`` dictionary?

**Comment by DirectXMan12** [comment]
> BTW, what other key-value pairs could be put in store dictionary?

It's implementation-specific, but for MIT krb5, the list is here: https://web.mit.edu/kerberos/krb5-1.13/doc/basic/ccache_def.html#ccache-types

**Comment by simo5** [comment]
To add to what @DirectXMan12 said, keywords are mechanism specific and other mechanisms may recognize different keywords. For example the gss-ntlmssp mechanism recognizes only the keyword **password** although there were plans to support also **client_keytab** and **keytab** if they had an RC4-HMAC key in it.

**Comment by tkdchen** [comment]
Hi, still a problem not resolved. How can I use a keytab to initialize a credential cache? Example given above

```
principal = gssapi.names.Name('HTTP/hostname@REALM',
                              gssapi.raw.NameType.kerberos_principal)
creds = gssapi.creds.Credentials(name=principal, usage='initiate')
```

it's just read rather than initialization.

**Comment by simo5** [comment]
You need to "acquire" credentials, but on top of that GSSAPI tries to delay the operation until credentials are actually needed.
You can force it by inspecting credentials and looking for their lifetime for example.
```check = creds.lifetime``` 
Requires MIT krb5 1.14 or later as in previous versions this was not reliable and you may get 0 as lifetime.

**Comment by tkdchen** [comment]
I get this error. There are already several tickets in credential cache ``FILE:/tmp/krb5cc_1000``.
```
>>> import gssapi
>>> store = {'keytab': '/path/to/httpd.keytab'}
>>> principal = gssapi.names.Name('HTTP/hostname@EXAMPLE.COM',
...                               gssapi.raw.NameType.kerberos_principal)
>>> creds = gssapi.creds.Credentials(name=principal, usage='initiate', store=store)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/gssapi/creds.py", line 64, in __new__
    store=store)
  File "/usr/lib64/python2.7/site-packages/gssapi/creds.py", line 148, in acquire
    usage)
  File "gssapi/raw/ext_cred_store.pyx", line 182, in gssapi.raw.ext_cred_store.acquire_cred_from (gssapi/raw/ext_cred_store.c:1892)
gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529639053): Can't find client principal HTTP/hostname@EXAMPLE.COM in cache collection
```

**Comment by simo5** [comment]
You should use a clean ccache file

**Comment by tkdchen** [comment]
@simo5 What do you mean by "a clean ccache file"? I tried following

```
$ kdestroy
$ klist
klist: No credentials cache found (filename: /tmp/krb5cc_1000)
```

But get same error above.

**Comment by simo5** [comment]
To do initialization you need to use 'client_keytab', not just 'keytab' in the store

**Comment by frozencemetery** [comment]
Please feel free to reopen or bother us on freenode/#python-gssapi if you have further questions.

**Comment by hbf0803** [comment]
@tkdchen  can you address this problem? When someone uses your project python-krbcontext.  https://github.com/pythongssapi/python-gssapi/issues/137  .  And i got the same problem.

**Comment by hbf0803** [comment]
when i type those code, raise exception like this:
>>> import gssapi
>>> store = {'client_keytab': '/path/to/httpd.keytab'}
>>> principal = gssapi.names.Name('hdfs/cloudera@HADOOP.COM',gssapi.raw.NameType.kerberos_principal)
>>> creds = gssapi.creds.Credentials(name=principal, usage='initiate', store=store)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python27/lib/python2.7/site-packages/gssapi/creds.py", line 64, in __new__
    store=store)
  File "/usr/local/python27/lib/python2.7/site-packages/gssapi/creds.py", line 140, in acquire
    raise NotImplementedError("Your GSSAPI implementation does "
NotImplementedError: Your GSSAPI implementation does not have support for manipulating credential stores


how can i address this problem with  gssapi 1.5.0  and os CentOS release 6.8 ?

**Comment by frozencemetery** [comment]
@hbf0803 Your issue is likely #137; let's keep the conversation there for the moment.

**Comment by gp1314** [comment]
@tkdchen I ran into the same problem using the username and password.

```
>>> import gssapi
>>> my_principle = gssapi.names.Name('test',gssapi.raw.NameType.user)
>>> creds_opts = {'usage': 'initiate','name': my_principle,}
>>> cred = gssapi.creds.Credentials(**creds_opts)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gssapi/creds.py", line 64, in __new__
    store=store)
  File "/usr/local/lib/python2.7/dist-packages/gssapi/creds.py", line 137, in acquire
    mechs, usage)
  File "gssapi/raw/creds.pyx", line 158, in gssapi.raw.creds.acquire_cred
gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529639053): Can't find client principal test@EXAMPLE.COM in cache collection
```
Any help would be much appreciated.
