### ISSUE TITLE
REALM.extract_keytab is hard to find

### ISSUE THREAD

**Issue by fbacchella** [pythongssapi/python-gssapi#113]
In documentation (https://pythonhosted.org/gssapi/basic-tutorial.html), you talk about an helper object call REALM. But if some one just read the doc, it come from nowhere. You talk about gssapi-console.py, but it's not in the core repository (python-gssapi), but in another (gssapi-console) but any way, the object is define in a third repository (https://github.com/pythongssapi/k5test). It make following the example harder to understand. Just a few lines about that would be helpful.

**Comment by frozencemetery** [comment]
I think this just needs an update since that's mentioned in the repo version.  @DirectXMan12, that gets updated automatically when we do a release, right?

**Comment by DirectXMan12** [comment]
yes, IIRC.  I can double check, though.

**Comment by DirectXMan12** [comment]
yep: https://github.com/pythongssapi/python-gssapi/blob/master/.travis.yml#L60

**Comment by frozencemetery** [comment]
We've released an update, so the docs should be good now.  Let us know if you find anything else!
