### ISSUE TITLE
Question about windows dns

### ISSUE THREAD

**Issue by yarara** [pythongssapi/python-gssapi#117]
Hello.
I need help.
I have windns server and i need update dns record in secure mode server.
How will i do this with use gssapi in python?

**Comment by frozencemetery** [comment]
Hi @yarara, thanks for your interest!  I'm not aware of any functionality in GSSAPI for manipulating DNS entries, especially not on windns.

**Comment by yarara** [comment]
@frozencemetery maybe you know any python libraries for manipulating DNS entries with credatials from gssapi?

**Comment by frozencemetery** [comment]
I do not, sorry.  Since you're using Windows, Microsoft probably has some functionality for this I would imagine?  None of us know Windows very well, especially as [freeIPA](http://www.freeipa.org/page/Main_Page) is a large consumer of python-gssapi.

**Comment by frozencemetery** [comment]
@yarara, @sigmaris has suggested that you may be after [GSS-TSIG](https://en.wikipedia.org/wiki/Generic_Security_Service_Algorithm_for_Secret_Key_Transaction)

**Comment by yarara** [comment]
@frozencemetery I'm looking for python library(linux) for manipulating DNS entries with use secure dns update(windows) from linux and used gss-tsig.
Example:
use python-gssapi for get credential and used it in another module/library.

But i can't find any library/

**Comment by simo5** [comment]
@yarara the easiest way is to use the nsupdate utility.
See nsupdate -g for gssapi support

**Comment by yarara** [comment]
@simo5 yes, now i use nsupdate from python.
