### ISSUE TITLE
Release v1.2.2

### ISSUE THREAD

**Issue by stanislavlevin** [pythongssapi/python-gssapi#129]
Hello.

There is a typo at commit [https://github.com/pythongssapi/python-gssapi/commit/32cb94cbb9dd8192904c572769eabefd6bd61f92](https://github.com/pythongssapi/python-gssapi/commit/32cb94cbb9dd8192904c572769eabefd6bd61f92) . Should be "Prepare for 1.2.2 Release" and please create corresponding tag(v1.2.2).

Thank you.

**Comment by DirectXMan12** [comment]
we already have a v1.2.2

**Comment by frozencemetery** [comment]
It's not uploaded anywhere because our release process is still broken.  At this point, I'm of the opinion that if neither of us can/will fix the automatic releases, maybe we should just do them by hand.

**Comment by stanislavlevin** [comment]
Some people work with tags(by manual or automatically). 
In my case, if i see a new version tag, i start to update package(from git repo).

**Comment by DirectXMan12** [comment]
whoops, apologies, I have a draft release tagged that I didn't notice was still marked as a draft, which is why I responded the way I did.  We also work off of tags too :-)

**Comment by DirectXMan12** [comment]
v1.2.4 is now in the process of releasing (the builds should be pushed to GitHub releases and PyPI as soon as this Travis build finishes: https://travis-ci.org/pythongssapi/python-gssapi/builds/309823554)
