### ISSUE TITLE
Add support for GSS_C_DELEG_POLICY_FLAG

### ISSUE THREAD

**Issue by frozencemetery** [pythongssapi/python-gssapi#132]
It's been present in MIT since krb5-1.8, and was added to heimdal at about the same time [the commit message](https://github.com/krb5/krb5/commit/45875a4d7bbd6bb8a943572d84fef5ca2bb18291).

I can't find a standard for it, but the Heimdal wrote up [a piece on its use](http://blog.h5l.org/2008/10/ok-as-delegate-and-gss-api.html).

**Comment by DirectXMan12** [comment]
especially since there's no standard, we'll want to make sure we have good docs in our docs for it.  Otherwise, we'd probably just want it to be its own extension (the tiniest extension).

**Comment by simo5** [comment]
@DirectXMan12 you want to copy in tree the Heimdal write up ?

**Comment by DirectXMan12** [comment]
That's probably fine.  I just like to make it so that our documentation can be used as a centralized place to see the basic mechanics of the APIs we support, since, for many of them, there's no easier place to go (I had to cobble a lot together from the krb5 wiki based on old info, for instance).
