### ISSUE TITLE
 /bin/sh: 1: krb5-config: not found

### ISSUE THREAD

**Issue by jqlinux** [pythongssapi/python-gssapi#134]
Collecting gssapi==1.2.3
  Downloading gssapi-1.2.3.tar.gz (873kB)
    Complete output from command python setup.py egg_info:
    In distributed package, building from C files...
    /bin/sh: 1: krb5-config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pycharm-packaging/gssapi/setup.py", line 56, in <module>
        link_args = get_output('krb5-config --libs gssapi')
      File "/tmp/pycharm-packaging/gssapi/setup.py", line 38, in _get_output
        res = subprocess.check_output(*args, shell=True, **kwargs)
      File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.5/subprocess.py", line 398, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command 'krb5-config --libs gssapi' returned non-zero exit status 127
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /tmp/pycharm-packaging/gssapi/

#sudo apt-get install krb5-config
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
krb5-config 已经是最新版 (2.6)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。

**Comment by tkdchen** [comment]
I think you need to install ``libkrb5-dev``, https://packages.debian.org/sid/libkrb5-dev

**Comment by frozencemetery** [comment]
@tkdchen is correct - you need libkrb5-dev on Debian (and if anyone finds this from search engine: krb5-devel on Fedora/CentOS/RHEL).  Beyond the krb5-config program, these packages provide the header files that we're going to link against (libgssapi).

**Comment by DirectXMan12** [comment]
(for further search engine folks, the equivalent to @frozencemetery's last command on Fedora/CentOS/RHEL is just to `yum install /usr/bin/krb5-config` or `dnf install /usr/bin/krb5-config`)

**Comment by jagadeeshposni** [comment]
I'm facing the same issue but with windows. Can you guys help me with the appropriate program to install in windows to get this running?

**Comment by DirectXMan12** [comment]
Windows is a bit tricky.  It also really depends on what environment you're using in Windows.  If you're using mingw, it should work similarly to the Linux setup instructions.  If not, it's probably decently more complicated.  @frozencemetery you have any tips?

**Comment by frozencemetery** [comment]
The irony of the guy with "DirectX" in his name asking me for tips :)

krb5-config is a driver program to find the header files for a GSSAPI installation.  Out of the box, Windows doesn't provide one of these; you're going to have to install one somehow.  As above, this will vary depending on what sub-environment you're using.  If you're in the Linux subsystem, just use the package manager; same with mingw.  MIT tests Windows using appveyor, so if it's helpful, here's [the driver file for that](https://github.com/krb5/krb5/blob/master/appveyor.yml).

If you run into trouble installing krb5 on Windows, I suggest you ask the kerberos mailing list - linked [here](http://web.mit.edu/kerberos/contact.html) (section "Getting Help for Administrators").  Hope that helps!

**Comment by JensTimmerman** [comment]
`libkrb5-dev` conflicts with `heimdal-dev` which is already on my system.
heimdal-dev provides krb5-config.mit (not krb5-config)

**Comment by frozencemetery** [comment]
@JensTimmerman what OS is this?  On Debian testing,

```
rharwood@seton:~$ apt-file show heimdal-dev | grep bin/krb5-config 
heimdal-dev: /usr/bin/krb5-config
rharwood@seton:~$ 
```

**Comment by JensTimmerman** [comment]
I'm sorry for the confusion, krb5-multidev was providing krb5-config.mit and is not a conflict. installing libkrb5-dev did fix my issues.
