### ISSUE TITLE
[travis] Don't fail "deploy latest docs" if there's nothing new to deploy

### ISSUE THREAD

**Issue by DirectXMan12** [pythongssapi/python-gssapi#136]
Currently, since both the actual commit job and the tag job run "deploy latest docs", there can be nothing to deploy (since the tag would be the same, even the "which tag did this build off of" file is the same).  We should either not fail when this happens, or not run "deploy latest docs" on tag deploys

**Comment by DirectXMan12** [comment]
Also seen on the cron job that runs periodically (we could just disable it there).

**Comment by frozencemetery** [comment]
(I had disabled it after it failed.)

**Comment by DirectXMan12** [comment]
you disabled the cron job?  That'll cause issues, since the cron job is what rebuilds the Docker images that we use to build.  I was suggesting just disabling the docs build if we're in a cron build.

**Comment by frozencemetery** [comment]
I didn't think we were using custom docker images for this yet?

**Comment by DirectXMan12** [comment]
oh, right, I never merged that.  Brain fart :-/

**Comment by DirectXMan12** [comment]
nevermind ;-)
