### ISSUE TITLE
lost gssapi.raw.ext_cred_store module

### ISSUE THREAD

**Issue by shm007g** [pythongssapi/python-gssapi#137]
when i use krbContext to download hdfs files in yarn cluster as below:

```
with krbContext(using_keytab=True, principal=principal, keytab_file=keytab_path):
            client = KerberosClient('http://{0}:50070'.format(server))
            client.download(os.path.join(HDFS_ROOT, hdfs_path), local_path, overwrite=True)
```
error happens here:
```
 with krbContext(using_keytab=True, principal=principal, keytab_file=keytab_path):
  File "/usr/local/anaconda3/lib/python3.5/site-packages/krbcontext/context.py", line 281, in __enter__
    self._prepare_context()
  File "/usr/local/anaconda3/lib/python3.5/site-packages/krbcontext/context.py", line 271, in _prepare_context
    self.init_with_keytab()
  File "/usr/local/anaconda3/lib/python3.5/site-packages/krbcontext/context.py", line 165, in init_with_keytab
    creds = gssapi.creds.Credentials(**creds_opts)
  File "/usr/local/anaconda3/lib/python3.5/site-packages/gssapi/creds.py", line 64, in __new__
    store=store)
  File "/usr/local/anaconda3/lib/python3.5/site-packages/gssapi/creds.py", line 140, in acquire
    raise NotImplementedError("Your GSSAPI implementation does "
NotImplementedError: Your GSSAPI implementation does not have support for manipulating credential stores
```
then i google it, i found this in gssapi code
![image](https://user-images.githubusercontent.com/16999665/34146073-8cfd8792-e4d3-11e7-8c99-0e7cb0feacff.png)
then i search for `rcred_cred_store `
![image](https://user-images.githubusercontent.com/16999665/34146171-e1184006-e4d3-11e7-8a11-e95c34fe4a6d.png)
then i search for `import_gssapi_extension`
![image](https://user-images.githubusercontent.com/16999665/34146124-b27d0c7c-e4d3-11e7-8a2b-0b3658dabc4d.png)

# OMG, lost one module!!!

```
>>> import gssapi
>>> import gssapi.raw
>>> import gssapi.raw.ext_cred_store
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'gssapi.raw.ext_cred_store'
```

**Comment by frozencemetery** [comment]
My guess is that you've built python-gssapi against a different version of Kerberos than you're running it against.

Can you provide some information so we can better investigate your problem, such as what operating system, where you got python-gssapi, what version it is, what version of Kerberos you're using with it, what version of Kerberos you built it against, etc.?

Also, we thought that error message was pretty descriptive - I can't tell what you're trying to convey with the pictures, except maybe that it's in our code (which of course it is)?

**Comment by hbf0803** [comment]
i got the same problem.

**Comment by shm007g** [comment]
I had tried that several days ago. It works fine when i update this dependency. @hbf0803

**Comment by hbf0803** [comment]
@shm007g  update which dependency ?  i installed  krbContext  with gssapi 1.5.0， which is the latest version. can you tell me to update what detail ?

**Comment by shm007g** [comment]
I'm not using this. I suggest you uninstall gssapi and reinstall, maybe restart your pc, test it afterwards. @hbf0803

**Comment by hbf0803** [comment]
can you show me the code using krbContext including import statement?  thanks .

**Comment by shm007g** [comment]
I' not using this anymore. I just test former import error and it works fine. You should find your own way, buddy. I can't help more.

**Comment by hbf0803** [comment]
Thank you very much ! @shm007g
