### ISSUE TITLE
Duplicate docs updates fail

### ISSUE THREAD

**Issue by frozencemetery** [pythongssapi/python-gssapi#140]
### What went wrong?

While trying to run CI in (weekly) cron, I noticed that the "deploy latest docs" does not work there, presumably because it's trying to push a hash which has already been pushed.

### How do we reproduce?

A failing build is [here](https://travis-ci.org/pythongssapi/python-gssapi/).

**Comment by DirectXMan12** [comment]
duplicate of #136
