### ISSUE TITLE
Create New Release?

### ISSUE THREAD

**Issue by jborean93** [pythongssapi/python-gssapi#144]
Nothing is wrong, was just hoping if a new release could be made to incorporate some of the changes been made recently?

**Comment by frozencemetery** [comment]
Hi, thanks for asking.  A minor release should be doable - I'll see if I can get that out today.

**Comment by frozencemetery** [comment]
Released 1.4.1.

**Comment by jborean93** [comment]
Thanks @frozencemetery (and the others) for all your help with this, much appreciated.
