### ISSUE TITLE
How to get  a  package with md5 authentication 

### ISSUE THREAD

**Issue by dawncc** [pythongssapi/python-gssapi#152]
We need a package to satisfy our security certification .
- the package should without c , which has may high Vulnerability.
- the package should delivery with md5 code.

so, how can I get this.

**Comment by simo5** [comment]
Sorry I do not understand this request.
If you need to satisfy security certifications, md5 is definitely not appropriate given it is truly and fully broken.
Python-gssapi is also a binding that uses FFI to interface with underlying GSSAPI libraries written in C, there is no "native python" implementation of GSSAPI.

Our releases are available here: https://github.com/pythongssapi/python-gssapi/releases
And all come with a SHA512 Summary.

Releases are also available here: https://pypi.python.org/pypi/gssapi
These seem to come with an MD5 Summary .. unfortunately.
