### ISSUE TITLE
store delegated creds to make query on behalf of 

### ISSUE THREAD

**Issue by belyaev-pa** [pythongssapi/python-gssapi#163]
Hello,

Sorry to post an issue for this but the doc is too hard to grasp. For example, I really can`t latch on what REALM is in the doc.
I would like to create a basic SPNEGO auth with Kerberos with delegating service client creds but it seems that I can't store creds after verify the users Negotiate token.

I want to make some steps:
1) return 401 for asking user`s Negotiate
2) verify user token by the server 
3) get the client principal
4) store client creds into krb5_ccache 
5) make a query into Postgresql via psycopg using GSSAPI, with cached krb5_ccache and principal behalf of the user.

```
`kind, client_token = request.META['HTTP_AUTHORIZATION'].split(' ', 1)
        if kind == 'Negotiate':
            os.environ['KRB5_KTNAME'] = 'FILE:/etc/httpd/http.keytab'
            os.environ['KRB5_CONFIG'] = '/etc/krb5.conf'
            ccache = os.environ['KRB5CCNAME'] = 'FILE:/tmp/krb5cc_%{uid}'
            service = 'HTTP@ksa1c1sb.che.ru'
            store = {'cchash': ccache}
            spnegoMechOid = gssapi.OID.from_int_seq("1.3.6.1.5.5.2")
            server_name = gssapi.Name(service, name_type=gssapi.NameType.hostbased_service)
            server_creds = gssapi.Credentials(usage='accept', name=server_name)
            ctx = gssapi.SecurityContext(creds=server_creds, usage='accept')
            server_tok = ctx.step(base64.b64decode(client_token))
            user_principal = ctx.target_name # what gives me server principal
            b64tok = base64.b64encode(server_tok)
            # here i need to store client ccache
            cl_creds = gssapi.Credentials(token=server_tok, store=store, usage='both')`
```

I had already realized this algorithm via [ccs-pykerberos](https://github.com/apple/ccs-pykerberos) (they have authGSSServerStoreDelegate() which provide to do it simple) but they have memory & file descriptors leaking issue.

I'm using python2, MIT Kerberos 5 on CentOS6 and 7
Thank you very much.

**Comment by simo5** [comment]
So you have quite a few issues in the snippet above.

1) The way you are setting the cache is problematic.
    - Setting the KRB5CCNAME environemnt variable is server wide
       It is not thread safe so it may interfere with other requests
       It will clobber the server's own ccache (that you create with the call that returns server_creds) once you try to set the client cache in there.
    - The value is not ok, substitutions happen only for ccache names set in krb5.conf.
      In this case the value will include the actual string '%{uid}'.
 
2) What's 'cchash' ? I think you meant 'ccache'
3) The user's principal is in ctx.initiator_name, not in target_name
       not that it really matters as you are not usinsg user_principal
4) Why are you passing the server token to a credentials call ?
    server_tok is a formatted message that makes sense only to a client
       (note: you are not sending it back to the client).

5) The user creds (if the user delegated them) are in ctx.delegated_creds.
    You can probably do something like: ctx.delegated_creds.store(store, usage='initiate')

I suggest you do not touch the server's KRB5CCNAME variable and store creds in a different file, then refer to that ccache file via calls like acquire_cred_from() to use them. If the software you are calling does not support anything else but a KRB5CCNAME env var I suggest you set the envvar on its popen() instead of server wide, if possible.

**Comment by belyaev-pa** [comment]
Thank you very much. It is very helpful.
I want to ask you more question if you allow:
1. What is the right and safe way to store creds?
2. How can i get principal from Name() class?

here is what i have now:

```
            os.environ['KRB5_KTNAME'] = 'FILE:/etc/httpd/http.keytab'
            os.environ['KRB5_CONFIG'] = '/etc/krb5.conf'            
            ccache = 'FILE:/tmp/krb5cc_0'
            store = {'ccache': ccache}
            service = 'HTTP@ksa1c1sb.che.ru'
            server_name = gssapi.Name(service, name_type=gssapi.NameType.hostbased_service)            
            server_creds = gssapi.Credentials(usage='accept', name=server_name)
            tok = base64.b64decode(client_token)
            ctx = gssapi.SecurityContext(creds=server_creds, usage='accept')
            server_tok = ctx.step(tok)            
            user_name = ctx.initiator_name# this get me Name() instance
            principal = user_name.attributes['name']# don`t work
            ctx.delegated_creds.store(store, usage='initiate', overwrite=True)
            conn = psycopg2.connect(
                host='ksa1c1-opkpudb',
                user=principal,
                dbname='SPODB',
            )
            cursor = conn.cursor()
            cursor.execute("SELECT version()")
            records = cursor.fetchall()
```

**Comment by frozencemetery** [comment]
Yes, KEYRING is a supported ccache type.  Note that we already default to using the default ccache; there's no need to read krb5.conf for this information.  Which is to say: all arguments to `creds.store()` are optional.
