### ISSUE TITLE
SecurityContext step()

### ISSUE THREAD

**Issue by jhnbyrn** [pythongssapi/python-gssapi#166]
This is probably just a documentation issue or a question I have and not a bug. I'm trying to use gssapi for spnego authentication with nginx on the backend. 

It's working for me, but what I'm doing doesn't seem to match what's described [here](https://pythongssapi.github.io/python-gssapi/stable/basic-tutorial.html) and in #165. 

My client code looks like this:

```
    name = gssapi.Name('HTTP/www.example.com')
    client_ctx = gssapi.SecurityContext(name=name, usage='initiate')
    initial_client_token = client_ctx.step()
    t = base64.b64encode(initial_client_token)
    headers = {'Authorization': 'Negotiate ' + t}
    r = requests.get('http://www.example.com/kerbtest/', headers=headers)
```
This works just fine. The URL is set up to require gssapi authentication, and I am getting access to it with the above code. But the links above state that I should be calling client_ctx() in a loop until client_ctx.complete is True. But what do I pass to it? The server is returning a Negotiate token in a www-Authenticate header, but if I call step with this token (after base64 decoding) then I get this exception:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "</home/kerbtestjohn/.virtualenvs/gssapi/lib/python2.7/site-packages/decorator.pyc:decorator-gen-9>", line 2, in step
  File "/home/kerbtestjohn/.virtualenvs/gssapi/lib/python2.7/site-packages/gssapi/_utils.py", line 167, in check_last_err
    return func(self, *args, **kwargs)
  File "</home/kerbtestjohn/.virtualenvs/gssapi/lib/python2.7/site-packages/decorator.pyc:decorator-gen-5>", line 2, in step
  File "/home/kerbtestjohn/.virtualenvs/gssapi/lib/python2.7/site-packages/gssapi/_utils.py", line 127, in catch_and_return_token
    return func(self, *args, **kwargs)
  File "/home/kerbtestjohn/.virtualenvs/gssapi/lib/python2.7/site-packages/gssapi/sec_contexts.py", line 521, in step
    return self._initiator_step(token=token)
  File "/home/kerbtestjohn/.virtualenvs/gssapi/lib/python2.7/site-packages/gssapi/sec_contexts.py", line 542, in _initiator_step
    token)
  File "gssapi/raw/sec_contexts.pyx", line 244, in gssapi.raw.sec_contexts.init_sec_context
gssapi.raw.exceptions.InvalidTokenError: Major (589824): Invalid token was supplied, Minor (100001): Success
```

I'm not sure if there's an issue here, since the initial authentication step does what I need  - but since this doesn't match what I've read, I'm just wondering, am I doing something wrong that could cause issues? 

Thanks!

### Component versions (python-gssapi, Kerberos, OS / distro, etc.)
python-gssapi 1.5.1 (client, installed with pip)
nginx/spnego-http-auth-nginx-module (server, built from latest source)
Kerberos 1.15.1 (MIT)
CentOS 7 (both client and server)

**Comment by simo5** [comment]
So a genaral comment.
Unfortunately a lot of software skips checking the returned token. In this case what they are going to miss is mutual authentication which means hey may be more subject to MITM attacks. However on the server side the authentication is effectively completed in the general case when using the krb5 mechanism as it is using only 2 steps in total (cli -> srv* / srv -> cli).
For other mechanisms (like NTLMSSP) this does not work as they need the third step from the client for the server to verify authentication (cli -> srv / srv -> cli / cli -> srv*) (the * denotes when the server has authenticated the client).

Now after this general comment, what you see should not happen and the client should in theory refuse to further talk to the server.

What this means for you.

In general it means that server replies are rarely tested (see general comment), so if the server side code is broken, often people will not notice, this puts you in the position of trying to figure out whether the server implementation is broken or there is a bug elsewhere in your code.
I would try to test it against a "known good" implementation. Afaik apache + mod_auth_gssapi will work correctly here. So if your code works or fails with that implementation you should know where you stand.

HTH.

**Comment by jhnbyrn** [comment]
Thanks, that explanation helps a lot. 

On further investigation, it's a bug in spnego-http-auth-nginx-module - that module truncates the token by 1 character.

**Comment by frozencemetery** [comment]
For closure, the bug in question is https://github.com/stnoonan/spnego-http-auth-nginx-module/issues/86
