### ISSUE TITLE
KafkaProducer - GSSAPI lib not available

### ISSUE THREAD

**Issue by arvj** [pythongssapi/python-gssapi#173]
**OS - Red Hat Enterprise Linux Server release 6.10 (Santiago)
Python3 - 3.7.1 - Anaconda3 Python
Python3 path - /opt/local/bgdatapp/anaconda3/bin/python
Kerberos - 5
Kafka - Cloudera 13.1**

I am able to access my kafka from shell and i am able to push and read messages.

`kafka-console-producer --broker-list host.domain.com:9092 --topic Topic1 --producer.config client.properties`

cat client.properties
_security.protocol=SASL_PLAINTEXT
sasl.kerberos.service.name=kafka_

`kafka-console-consumer --topic Topic1 --consumer.config consumer.properties --bootstrap-server host.domain.com:9092 --from-beginning`

cat consumer.properties
_security.protocol=SASL_PLAINTEXT
sasl.kerberos.service.name=kafka_

Simulating the same from python
I am writing a python program to connect to Kafka and read/write message.

Producer error on executing **python3 producer.py**

  File "/opt/local/bgdatapp/anaconda3/lib/python3.7/site-packages/kafka/conn.py", line 255, in __init__
    assert gssapi is not None, 'GSSAPI lib not available'
AssertionError: GSSAPI lib not available
Exception ignored in: <function BrokerConnection.__del__ at 0x7f715f4b3378>
Traceback (most recent call last):
  File "/opt/local/bgdatapp/anaconda3/lib/python3.7/site-packages/kafka/conn.py", line 696, in __del__
    self._close_socket()
  File "/opt/local/bgdatapp/anaconda3/lib/python3.7/site-packages/kafka/conn.py", line 691, in _close_socket
    if self._sock:
AttributeError: 'BrokerConnection' object has no attribute '_sock'
INFO:kafka.producer.kafka:Kafka producer closed

Python code:
```
import os
import socket
import gssapi
import logging
from kafka import KafkaProducer
KAFKA_TOPIC = 'Topic1'
KAFKA_BROKERS = 'host.domain.com:9092'
os.environ['KAFKA_OPTS'] = '-Djava.security.auth.login.config=/opt/local/account1/jaas.conf'
logging.basicConfig(level=logging.INFO)

messages = [b'hello kafka', b'I am sending', b'3 test messages']

producer = KafkaProducer(bootstrap_servers=KAFKA_BROKERS, api_version=(0, 10), security_protocol='SASL_PLAINTEXT', sasl_mechanism='GSSAPI', sasl_kerberos_service_name='kafka', max_request_size=3173440261)

for m in messages:
	print (producer.send(KAFKA_TOPIC, m).get(timeout=30))
```

**Comment by frozencemetery** [comment]
Anaconda python is not a supported python installation, as I said in #171: " In order to run python-gssapi here, you need to use the python-3.6 from epel6 in a virtualenv."
