### ISSUE TITLE
KafkaConsumer - Unable to bootstrap from

### ISSUE THREAD

**Issue by arvj** [pythongssapi/python-gssapi#174]
I am able to access my kafka from shell and i am able to push and read messages.

`kafka-console-consumer --topic Topic1 --consumer.config consumer.properties --bootstrap-server host.domain.com:9092 --from-beginning`

> cat consumer.properties
> security.protocol=SASL_PLAINTEXT
> sasl.kerberos.service.name=kafka

**OS - Red Hat Enterprise Linux Server release 6.10 (Santiago)
Python3 - 3.7.1 - Anaconda3 Python
Python3 path - /opt/local/bgdatapp/anaconda3/bin/python
Kerberos - 5
Kafka - Cloudera 13.1**

Simulating the same from python
I am writing a python program to connect to Kafka and read/write message.

Consumer error when executing **python3 consumer.py**

WARNING:kafka.consumer.group:use auto_offset_reset=earliest (smallest is deprecated)
INFO:kafka.client:Bootstrapping cluster metadata from [('host.domain.com', 9092, <AddressFamily.AF_UNSPEC: 0>)]
INFO:kafka.conn:<BrokerConnection node_id=bootstrap host=host.domain.com:9092 <connecting> [IPv4 ('11.22.33.44', 9092)]>: connecting to host.domain.com:9092 [('11.22.33.44', 9092) IPv4]
INFO:kafka.conn:<BrokerConnection node_id=bootstrap host=host.domain.com:9092 <connecting> [IPv4 ('11.22.33.44', 9092)]>: Connection complete.
**ERROR:kafka.conn:<BrokerConnection node_id=bootstrap host=host.domain.com:9092 <connected> [IPv4 ('11.22.33.44', 9092)]>: socket disconnected**
INFO:kafka.conn:<BrokerConnection node_id=bootstrap host=host.domain.com:9092 <connected> [IPv4 ('11.22.33.44', 9092)]>: Closing connection. KafkaConnectionError: socket disconnected
**ERROR:kafka.client:Unable to bootstrap from [('host.domain.com', 9092, <AddressFamily.AF_UNSPEC: 0>)]**
INFO:kafka.consumer.subscription_state:Updating subscribed topics to: ('Topic1',)

Python code:
```
import os
import socket
import gssapi
import logging
from kafka import KafkaConsumer
KAFKA_TOPIC = 'Topic1'
KAFKA_BROKERS = 'host.domain.com:9092'
os.environ['KAFKA_OPTS'] = '-Djava.security.auth.login.config=/opt/local/account1/jaas.conf'
logging.basicConfig(level=logging.INFO)

consumer = KafkaConsumer("Topic1", group_id='None', bootstrap_servers=['tcx-tpapl00223-n9.tfs.toyota.com:9092'], api_version=(0, 10), auto_offset_reset='smallest', security_protocol="PLAINTEXT", sasl_kerberos_service_name='kafka')
```

**Comment by frozencemetery** [comment]
Anaconda python is not a supported python installation, as I said in #171: " In order to run python-gssapi here, you need to use the python-3.6 from epel6 in a virtualenv."
