### ISSUE TITLE
Support mutating the existing credentials object with add_cred

### ISSUE THREAD

**Issue by DirectXMan12** [pythongssapi/python-gssapi#18]
We should support mutating the current credentials object with `add_cred`, which is possible if `NULL` is passed as the output cred object in the C API.  We should follow up with a change to the high-level API

**Comment by DirectXMan12** [comment]
Another option would be to have `add` mean 'add to existing' and create a new method for 'add to new set' (or vice versa).

**Comment by frozencemetery** [comment]
Awesome, LGTM so long as travis passes.
