### ISSUE TITLE
gssapi interface for Django

### ISSUE THREAD

**Issue by bdauvergne** [pythongssapi/python-gssapi#185]
Nothing wrong here, just to signal https://pypi.org/project/django-gssapi/, and thank you for python-gssapi, it's lot clearer than pykerberos.

**Comment by bdauvergne** [comment]
I still have a question. I would like to have full coverage of my code, for coverage bingo, but I don't how to have a non-complete SPNEGO exchange after receiving initiator token (there https://jenkins2.entrouvert.org/job/django-gssapi/job/master/Coverage_20Report_20_28native_29/), do you know a way to do it with Kerberos or another GSSAPI mechanism ?

**Comment by simo5** [comment]
Would corrupting the token so that the exchange fails help ?

**Comment by bdauvergne** [comment]
That's ok for the except case with GSSError, but what I'm looking for is a case where `server_ctx.step()` works and returns an out_token but `server_ctx.complete` would be false. I'm not sure it can happen with SPNEGO/Kerberos.

**Comment by simo5** [comment]
With regular kerberos it can't, as the server performs only one step.
You can do it with SPNEGO/NTLMSSP as that requires two steps on the server.

**Comment by simo5** [comment]
(All you need is gssntlmssp installed to be able to test SPNEGO/NTLMSSP)
