### ISSUE TITLE
How to set several flags in SecurityContext?

### ISSUE THREAD

**Issue by ChmutovSergey** [pythongssapi/python-gssapi#187]
I want set next flags: 

- gelegate_to_peer=1
- replay_detection=4
- transferable=256

May be:
`client_ctx = gssapi.SecurityContext(name=server_name, 
                                                            usage='initiate', 
                                                            flags=(1|4|256))
`
or 
`client_ctx = gssapi.SecurityContext(name=server_name, 
                                                            usage='initiate', 
                                                            flags=261)
`

**Comment by frozencemetery** [comment]
It's passed as a list.  Idiomatically, this would be something like:

```
flags = [gssapi.RequirementFlag.delegate_to_peer,
          gssapi.RequirementFlag.replay_detection,
          gssapi.RequirementFlag.transferable]
ctx = gssapi.SecurityContext(name=sname, usage="initiate", flags=flags)
```
