### ISSUE TITLE
setup.py should have python_requires

### ISSUE THREAD

**Issue by jborean93** [pythongssapi/python-gssapi#198]
### What went wrong?
The new 1.6.4 release dropped support for Python 2.7 and 3.5 which is fine but when a user goes to `pip install gssapi` on those hosts it will install 1.6.4 when 1.6.2 should really be the one to install.

I'm not sure if we can actually do anything for this now a release is out but it would be good to avoid this in the future when a Python version is dropped. IIRC to do this you just need to add `python_requires` to setup.py which is what Ansible is doing https://github.com/ansible/ansible/blob/148e83f832aafa27bb49e98667bdcf72f1fd0f84/setup.py#L277. For this project it should be `python_requires=">=3.6.*"`

### How do we reproduce?

`pip install gssapi` on a Python 2.7 or 3.5. The install works fine but when you go to use the library 3.6 specific syntax will cause a failure. Ideally a pip install on those version should select the latest version that is supported for that Python version.

### Component versions (python-gssapi, Kerberos, OS / distro, etc.)

Install through pip on Python 2.7 and/or 3.5.

**Comment by briantist** [comment]
Thanks for submitting this; this burned me hard yesterday.

**Comment by frozencemetery** [comment]
Ah, will fix in a moment.  Thanks for pointing this out.

We aren't interested in python 2 - it's done upstream and we haven't supported it since January.  However, 3.5 is still supported upstream, so I'll adjust this.

**Comment by frozencemetery** [comment]
I've unpushed the 1.6.4 release from pypi and will cut a 1.6.5 with the changes from #199.  This should fix the problems observed, I think.
