### ISSUE TITLE
Credential store issue on 1.6.7

### ISSUE THREAD

**Issue by DavidVentura** [pythongssapi/python-gssapi#213]
### What went wrong?

After upgrading from 1.6.5 to 1.6.7 I started getting the error `Your GSSAPI implementation does not have support for manipulating credential stores`

### How do we reproduce?

```
     with krbcontext.krbContext(using_keytab=True,
                                principal=settings.KRB_PRINCIPAL,
                                keytab_file=settings.KEYTAB_FILE):
       pass
```

The only change between a working and a broken environment is running
`pip install gssapi==1.6.5` (and `.7` for the broken environment)

### Component versions (python-gssapi, Kerberos, OS / distro, etc.)

CentOS 7.6
krb5-libs-1.15.1-37.el7_6.x86_64

```
krbcontext==0.10
pykerberos==1.2.1
requests-kerberos==0.12.0
```

gssapi was being pulled (and got upgraded) from an unpinned `gssapi` dependency in the krbcontext package.

I can provide any extra info you need

**Comment by frozencemetery** [comment]
1.6.7 shouldn't have been released.  I've yanked it.  Thanks for your report!
