### ISSUE TITLE
Build script fails on Windows with the next error "build\lib.win-amd64-3.8\gssapi\raw\ext_cred_store.cp38-win_amd64.pyd : fatal error LNK1120: unresolved external elements: 3"

### ISSUE THREAD

**Issue by Shumodan** [pythongssapi/python-gssapi#214]
### What went wrong?
Building fails on windows

ext_cred_store.obj : error LNK2001: unresolved externalsymbol igss_store_cred_into.
ext_cred_store.obj : error LNK2001: unresolved externalsymbol igss_add_cred_from.
ext_cred_store.obj : error LNK2001:  unresolved externalsymbol igss_acquire_cred_from.
build\lib.win-amd64-3.8\gssapi\raw\ext_cred_store.cp38-win_amd64.pyd : fatal error LNK1120: нunresolved external elements: 3

### How do we reproduce?
Try to run 'python setup.py build' on Windows 

### Component versions (python-gssapi, Kerberos, OS / distro, etc.)
python-gssapi - 1.6.7
Kerberos - MIT Kerberos Version 4.1
OS - Win10 x64

**Comment by frozencemetery** [comment]
Dup of #213
