### ISSUE TITLE
Port away from should_be

### ISSUE THREAD

**Issue by frozencemetery** [pythongssapi/python-gssapi#215]
should_be doesn't work with python-3.8 and it's unmaintained, so we need something else before fc31 testing stops being viable.

**Comment by stanislavlevin** [comment]
Hi, @frozencemetery. Some time ago I filed the identical issue https://github.com/pythongssapi/python-gssapi/issues/130. Since that time I build python-gssapi for my distro without `should_be`. If somebody interests I could open related PR.

**Comment by frozencemetery** [comment]
Unless I'm missing something, #130 is for something different: our test suite works just fine up through 3.7 as far as I can tell.  (Certainly it works on fedora 31, which is python3-3.7.8-1.fc31, so...)

I am of course happy to consider pull requests to address this issue :)  Please do submit them in the form of pull requests (and not attached .patch files).
