### ISSUE TITLE
gssapi 1.6.12 won't import on Python 3.10

### ISSUE THREAD

**Issue by ronf** [pythongssapi/python-gssapi#239]
### What went wrong?

gssapi import fails on Python 3.10 on macOS due to a missing symbol of __PyGen_Send:

```
Python 3.10.0a4 (default, Jan  7 2021, 19:49:07) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gssapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gssapi/__init__.py", line 31, in <module>
    from gssapi.raw.types import NameType, RequirementFlag, AddressType  # noqa
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gssapi/raw/__init__.py", line 50, in <module>
    from gssapi.raw.creds import *  # noqa
  File "gssapi/raw/creds.pyx", line 1, in init gssapi.raw.creds
ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gssapi/raw/oids.cpython-310-darwin.so, 2): Symbol not found: __PyGen_Send
  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gssapi/raw/oids.cpython-310-darwin.so
  Expected in: flat namespace
 in /opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gssapi/raw/oids.cpython-310-darwin.so
```

It appears that PyGen_Send() has been replaced with PyIter_Send() in Python 3.10.

### How do we reproduce?

Try to import gssapi from Python 3.10.

*(Remember to use fenced code blocks and consider placing in a gist if large)*

### Component versions (python-gssapi, Kerberos, OS / distro, etc.)

*(Please include MIT/Heimdal/etc. and how you installed python-gssapi)*

Python: 3.10.0a4 (default, Jan  7 2021, 19:49:07) 
gssapi: 1.6.12

I installed gssapi via pip (version 20.2.3).

**Comment by jborean93** [comment]
The C code that generates this file is generated from Cython so I'm wondering if this is a bug there. Will have to install Python 3.10 on my macOS host and play with it a bit more.

**Comment by jborean93** [comment]
A quick search brings up https://github.com/cython/cython/issues/3876 which indicates it has been fixed in the code it's just not present in a release yet. I'm not sure if we can fix this without the changes from Cython to generate the code with the new API.

**Comment by jborean93** [comment]
I can confirm that installing Cython from source allows it to build this library correctly for Python 3.10. I tested both the `0.29.x` and `master` (upcoming 3.x releases) branches.

I don't think we are really in a position to do anything about this for now. We probably have to wait until both 3.10 is in a beta or rc state to judge whether we need to do anything extra for that version and hopefully by that time Cython has a release in place that includes their fix.

**Comment by ronf** [comment]
Thanks very much for looking into this!

If the actual change needed is in Cython, I agree there's not really anything to do for now in gssapi. I only noticed this because I was testing my code across a range of Python versions (3.6 to 3.10) and I happened to notice that it was automatically skipping the GSSAPI unit tests on 3.10 but not elsewhere. It turned out it was due to the failure I reported here when doing the gssapi import.

It's good to know that the Cython fix is already available, even if it's not in a release yet.

**Comment by frozencemetery** [comment]
python-3.10rc1 has landed in Fedora rawhide, so I took a look at this.  With python3-Cython-0.29.24-1.fc35.x86_64 and python3-3.10.0~rc1-1.fc35.x86_64, we build, install, and import without error on my VM.  So I'm going to close this.
