### ISSUE TITLE
Get rid of MIT Kerberos dependency on Windows

### ISSUE THREAD

**Issue by christophvw** [pythongssapi/python-gssapi#244]
Having to install MIT Kerberos on every machine is a show stopper on windows.

-It cannot be installed by pip on per user basis.
-it comes with a process with runs in the background the whole time
-the user gets notifications when a ticket is about to expire and on other failues -> will result in extra work for the helpdesk

Would it be possible to use this instead?
https://github.com/apple/ccs-pykerberos

**Comment by jborean93** [comment]
I mentioned this in IRC #python-gssapi but this isn't possible right now. This library uses the GSSAPI API which is commonly provided by library like MIT Kerberos or Heimdal. Windows doesn't have a GSSAPI library builtin but uses something called SSPI. This is pretty much the same thing but the API is completely different so python-gssapi cannot interact with this without extra code to handle all that.

Using something like https://github.com/apple/ccs-pykerberos also won't work as just like python-gssapi it uses the GSSAPI API and would also require a GSSAPI library to be installed on Windows, like MIT Kerberos. If you want something that works with the native SSPI to use Kerberos there are 3 options available to you

* [pywin32](https://github.com/mhammond/pywin32)
* [winkerberos](https://github.com/mongodb/winkerberos)
* [pyspnego](https://github.com/jborean93/pyspnego)

I would personally avoid winkerberos as it's designed as an API equivalent of ccs-pkerberos/pykerberos and it's not the easiest API to use. The `pywin32` library is a very popular Windows library that exposes the SSPI functions and I would highly recommend you use it over `winkerberos`. The `pyspnego` library is one I've written that wraps this library and my own SSPI integration code and exposes a single API for both platforms. It's relatively new but you are more than welcome to try it out if you like.

**Comment by frozencemetery** [comment]
You might also find the SSPI/GSSAPI bridge interesting, depending on your use case: https://github.com/nicowilliams/gsskrb5 (or https://github.com/twosigma/gsskrb5 - I can't tell which is the proper one).  Note that I haven't used this myself and can't vouch for its current state.

Intricate Windows support work is usually beyond what I can justify doing for work on this project - what we have for non-Linux is primarily due to the efforts of audirog and jborean.  So since Jordan recommends pyspnego, I'd second that recommendation :)

**Comment by HenriWahl** [comment]
Greetings from 2 years later... just found this issue which seems to cover my problem too.
Can you give me an example, how to use `requests-gssapi`instead of `python-kerberos on Windows? Looks like it is meant to use `pyspnego` but I do not find how. Thanks for any help!

**Comment by prusswan** [comment]
For Windows, `python-kerberos` + `pyspnego` will work without requiring KfW (just don't install `python-gssapi`)

https://stackoverflow.com/questions/71549322/how-to-get-a-kerberos-token-in-python-i-have-working-c-sharp-and-ps-syntax-but
