### ISSUE TITLE
Cannot store credentials to default ccache

### ISSUE THREAD

**Issue by tkdchen** [pythongssapi/python-gssapi#256]
### What went wrong?

I have a piece of code that acquires credential by calling function `acquire_cred_with_password`, and then store it into the default ccache. The problem is when the default ccache does not exist, the `store_cred` function always raises the following error.

`gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529639107): No credentials cache found`

`store_cred` does not work as well in following cases:

- The default ccache file, e.g. `/tmp/krb5cc_0`, exists and is empty, the function reports `gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529639111): Bad format in credentials cache`
- `KRB5CCNAME` is set to an existing empty file, the same error is reported.
- `KRB5CCNAME` is set to ~~an empty file which does not exist~~ a file and that file does not exist yet, the above `Minor (2529639107): No credentials cache found` is reported.

The non-existing default ccache could be the cases, for example, the file `/tmp/krb5cc_%{uid}` does not exist or the ccache managed by KCM (tested on Fedora 34) is empty.

The similar code works well for storing the credentials acquired by a keytab. After researching the documentation and even the source code, I haven't figured out why it does not work for the credentials acquired by a user principal and password. I'm not sure if anything I misunderstand or some other code is required before storing the credentials.

### How do we reproduce?

This example code to reproduce:

```python
import gssapi
from gssapi._utils import import_gssapi_extension

rcred_rfc5588 = import_gssapi_extension('rfc5588')

def store_cred_into_default_ccache():
    princ = gssapi.Name("user1", name_type=gssapi.NameType.user)
    cred = gssapi.raw.acquire_cred_with_password(princ, b"pass")
    rcred_rfc5588.store_cred(cred.creds, usage="initiate", overwrite=True, set_default=True)
```

### Component versions (python-gssapi, Kerberos, OS / distro, etc.)

Component | CentOS 8 container | Fedora 34 (with KCM backend) 
--- | --- | ---
python3-gssapi | 1.5.1 | 1.6.9
krb5 | 1.18.2 | 1.19.1

**Comment by frozencemetery** [comment]
Having some trouble understanding what you're doing, so here are some thoughts:

- Empty files are not valid ccaches; storing into them won't work
- What do you mean by "an empty file which does not exist"?
- The report indicates KCM is in use for some cases - have you checked sssd-kcm is running etc.?
- There's example code, yes, but it's not clear how to use it to reproduce.  Can you indicate what the default ccache setting is for each case you think is a problem, along with the condition of ccache/system?

**Comment by tkdchen** [comment]
> Empty files are not valid ccaches; storing into them won't work

An empty file can be created by `touch`, for example, `touch /tmp/temp_cc`, the `store_cred_into` is able to store the credentials to that file:

```python
    rcred_cred_store.store_cred_into(
        {b"ccache": b"/tmp/temp_cc"}, cred.creds,
        usage="initiate", overwrite=True, set_default=True
    )
```

however, if create an empty file for current user, e.g.  `touch /tmp/krb5cc_0`, or point to an alternative empty file by setting the `KRB5CCNAME`, `store_cred` fails to store the credentials into the file and reports `Bad format in credentials cache`. Example steps to reproduce:

```bash
touch /tmp/temp_cc
export KRB5CCNAME=/tmp/temp_cc
python3 -c "
import gssapi
from gssapi._utils import import_gssapi_extension
rcred_rfc5588 = import_gssapi_extension('rfc5588')
princ = gssapi.Name("user1", name_type=gssapi.NameType.user)
cred = gssapi.raw.acquire_cred_with_password(princ, b"pass")
rcred_rfc5588.store_cred(
    cred.creds, usage="initiate", overwrite=True, set_default=True
)
"
```

You can replace the username and password accordingly when reproduce.

> What do you mean by "an empty file which does not exist"?

Sorry, it should be "KRB5CCNAME is set to a file and that file does not exist".

> The report indicates KCM is in use for some cases - have you checked sssd-kcm is running etc.?

Yes. sssd-kcm is running. To reproduce, run `kdestroy` firstly and ensure `klist` outputs like `klist: Credentials cache 'KCM:1000' not found`.

> There's example code, yes, but it's not clear how to use it to reproduce. Can you indicate what the default ccache setting is for each case you think is a problem, along with the condition of ccache/system?

For the KCM case, the default ccache setting is `default_ccache_name = KCM:`.

When mentioning the default ccache, I mean my understand of the execution of `store_cred` is, it follows the default behavior to resolve the ccache, the one specified by KRB5CCNAME, the one set in the krb5.conf, or the krb5 default ccache name `FILE:/tmp/krb5cc_%{uid}`.

**Comment by frozencemetery** [comment]
> An empty file can be created by touch, for example, touch /tmp/temp_cc, the store_cred_into is able to store the credentials to that file:

You're getting lucky :)  I would recommend not depending on this behavior - again, an empty file is *not* a valid ccache.  In any case, it comes from krb5, not python-gssapi.

> Sorry, it should be "KRB5CCNAME is set to a file and that file does not exist".
>
> Yes. sssd-kcm is running. To reproduce, run kdestroy firstly and ensure klist outputs like klist: Credentials cache 'KCM:1000' not found.

For both of these cases, the underlying issue is in krb5 and is tracked as https://krbdev.mit.edu/rt/Ticket/Display.html?id=8010 - I'm therefore closing this ticket.

For your case, what I suggest you do is use the cred store extension rather than relying on the environment variable.  So something like:

```python
import gssapi

cname = gssapi.Name("user1", name_type=gssapi.NameType.user)
res = gssapi.raw.acquire_cred_with_password(cname, b"pass")

# convert the raw creds object into the high-level interface
creds = gssapi.Credentials(res.creds)

# underlying raw call is store_cred_into
creds.store(store={"ccache": "FILE:/tmp/testcc"}, overwrite=True)
```

Hope that helps.
