### ISSUE TITLE
Undocumented units of time

### ISSUE THREAD

**Issue by judilsteve** [pythongssapi/python-gssapi#277]
I cannot find a single mention of a unit of time in the [documentation](https://pythonhosted.org/gssapi/gssapi.html) of the high level API.

E.g. I can acquire a credential and I know that it has a lifetime of "36000"; a value which is totally useless because I don't know if it's 36000 seconds, milliseconds, minutes, hours, millenia?

**Comment by jborean93** [comment]
I'm pretty sure the lifetime values for both the security context and credential are measured in seconds. For example [gss_acquire_cred](https://datatracker.ietf.org/doc/html/rfc2744#section-5.2) `time_req` states

> Integer, read, optional
> number of seconds that credentials
> should remain valid. Specify GSS_C_INDEFINITE
> to request that the credentials have the maximum
> permitted lifetime.

The [gss_init_sec_context](https://datatracker.ietf.org/doc/html/rfc2744#section-5.19) call also mentions the same. Will have to update the documentation when I get a chance. Feel free to send through a PR if you find some time.

**Comment by judilsteve** [comment]
https://github.com/pythongssapi/python-gssapi/pull/278

**Comment by jborean93** [comment]
Fixed with https://github.com/pythongssapi/python-gssapi/pull/285
