### ISSUE TITLE
Error when installing gssapi on Google colab env

### ISSUE THREAD

**Issue by pentium84** [pythongssapi/python-gssapi#288]
### What went wrong?
I can not install gssapi package . I am gettting an errror when installing it

![image](https://user-images.githubusercontent.com/16207229/156821560-a0fe0811-73bf-4e1b-a3c3-73311c478f85.png)

### How do we reproduce?
Using google colab, run one or both of this code snippet

pip install --upgrade pip
pip install gssapi

*(Remember to use fenced code blocks and consider placing in a gist if large)*

### Component versions (python-gssapi, Kerberos, OS / distro, etc.)
python-gssapi
*(Please include MIT/Heimdal/etc. and how you installed python-gssapi)*
I used pip install using Google colab

**Comment by jborean93** [comment]
This library requires a gssapi library like MIT krb5 or Heimdal to he installed. Part of those package is the `krb5-config` command which the installation uses to figure out how to compile the C extensions. If this is missing you typically get a failure like this. I have no idea if you can install those gssapi libraries in this type of environment as I’ve never used it before but it is a hard requirement.

**Comment by cloudripper** [comment]
You need to install krb5 dev package (libkrb5-dev)

[](https://github.com/apple/ccs-pykerberos/issues/66)

**Comment by jborean93** [comment]
Closing as per the above, the required C libraries and `krb5-config` need to be present to be able to compile the C code for gssapi.
