### ISSUE TITLE
Broken links to documentation in the README

### ISSUE THREAD

**Issue by Wouterkoorn** [pythongssapi/python-gssapi#305]
The links to the documentation in the README both point to a 404

- https://pythongssapi.github.io/python-gssapi/stable
- https://pythongssapi.github.io/python-gssapi/latest

**Comment by jborean93** [comment]
Thanks for picking this up, looks like the base URL was changed but the `stable` and `latest` paths were kept. GitHub docs doesn't have this setup as it's now just a single URL. The PR https://github.com/pythongssapi/python-gssapi/pull/306 fixes the docs.
