### ISSUE TITLE
Support Windows?

### ISSUE THREAD

**Issue by DirectXMan12** [pythongssapi/python-gssapi#32]
We may wish to consider supporting Windows at some point

**Comment by filmor** [comment]
What needs to be done to get there?

**Comment by DirectXMan12** [comment]
1. Compilation needs to be tested in Windows with MIT Kerberos for Windows on MinGW.
2. The conditional compilation logic needs to be adjusted to work for Windows
3. We need a way to build wheels for windows (optional, but useful for anyone who actually wants to use this on Windows).

**Comment by frozencemetery** [comment]
Other "nice to have" - some way to run our test suite, since I don't think k5test will work there.

**Comment by ibigpapa** [comment]
So using the MIT KfW.  I see the source is available as well as precompiled sources could we just wrap these to make it work?

**Comment by DirectXMan12** [comment]
yeah, it really comes down to finding time and a windows box to test on (plus setting up CI to make sure we don't break anything), plus tweaking `setup.py` to work properly on Windows.

**Comment by ibigpapa** [comment]
I'm working on trying to hack this in myself let you know how i do.

**Comment by DirectXMan12** [comment]
cool.  Feel free to ping us on #python-gssapi on freenode if you have any questions best answered in a real-time manner (I'm usually on from 10:00-17:00EST)

**Comment by frozencemetery** [comment]
2a2b47b6f35a0058eb8c33e23e7630f6ecdbf5d1 adds support for conditional compilation.  Still missing are building wheels and running buildjob CI.  Much like with Heimdal, a stretch goal is to port k5test so we can run the test suite there.

**Comment by aiudirog** [comment]
I've been working on Windows support the past couple of days to get my company to move off of requests-kerberos (I had previously patched ccs-kerberos to work on Windows) and got everything to compile properly under VS Build Tools, MinGW, and MSYS. Unfortunately I won't be able to test until I'm back at work on Monday since k5test isn't ported yet. [My current progress can be found here.](https://github.com/aiudirog/python-gssapi/tree/aiudirog-win32-support) 

Changes:
- I created a predefined macro (`__MSYS__`) to allow the header files to detect MinGW under MSYS so that when it isn't under it, they can target MIT Kerberos for Windows instead (which also seems to have better extension support). 
- To get it compile under VS:
    - I had to cast all slicing of `gss_buffer_desc.values` to `char*` because many platforms  seem to declare it as a `void*` instead and cl.exe doesn't like `void*` pointer arithmetic. [This can be found a separate commit.](https://github.com/aiudirog/python-gssapi/commit/611b1f1198f77690f2e835fa8ef1784e11b84da4)
    - `libraries` is now passed separately to Extension like `library_dirs` so that Extension itself can determine how to pass them to the linker.
- `link_args` and `compile_args` are now always lists. This is to support arguments which may have spaces in them, like include paths on Windows.

**Comment by aiudirog** [comment]
Everything seems to be working as expected. I was able to connect to our internal Apache Livy and Phoenix servers on Windows and use them as normal through requests-gssapi.

**Comment by frozencemetery** [comment]
That's awesome, well done!  Do you have any idea how this could be tested in CI?  (Presumably just checking that the build works, as we do with Heimdal, since the krb5 server parts don't run on Windows, but don't let me stop you if you're feeling ambitious.)

**Comment by aiudirog** [comment]
I've been looking into it and Travis does support Windows now so I'll put some work into at the very least getting it to build and generate wheels.

**Comment by aiudirog** [comment]
I've opened a pull request to start playing with the Travis build. Hopefully this goes more smoothly than I'm expecting.

**Comment by aiudirog** [comment]
@frozencemetery I have it building on 2.7, 3.6, and 3.7 on Windows and I think I configured the deployment right, though I'm not sure. This is my first time using Travis (only experience with Jenkins, though I'm liking Travis a lot) so I might have missed something. Is there any way to do a mock deployment to test it?

**Comment by frozencemetery** [comment]
Either you figured it out, or I'm not understanding the question :)  Please post a comment in that PR when it's ready for review.

**Comment by aiudirog** [comment]
My question was purely about deploying the wheels. Not sure if I set it up right since you can't test deployment from a PR. I guess we can test once it's merged.

**Comment by frozencemetery** [comment]
@aiudirog So I ran into some problems trying to cut a release for this.  I made some fixes - a6e3f0868b7430ee5dcf9e4bf45047f6cfbd84c6 and 5c80107c84d5d3181dfdacb0c0c1725d77785d72 - but then I ran into failure trying to use pypi - [first](https://travis-ci.org/pythongssapi/python-gssapi/jobs/559593571) [second](https://travis-ci.org/pythongssapi/python-gssapi/jobs/559593573) and [third](https://travis-ci.org/pythongssapi/python-gssapi/jobs/559593574) subjobs.

It seems to me - and please let me know if this isn't right - that we can't build wheels from Travis right now.  That being the case, how would you feel about using Appveyor for this instead?  (I think that works...)

**Comment by neirbowj** [comment]
I just have to say---and I know that this isn't necessarily appropriate for an issue thread---that I really appreciate the work each of you is doing to help achieve this. I wish there were more I could do to help move things along.

**Comment by aiudirog** [comment]
[This seems to be the issue to keep an eye on."](https://github.com/travis-ci/dpl/issues/1009)

For now, we can probably just manually upload using a script deployment and twine. I'm going to give that a try before redoing the whole thing in Appveyor.
