### ISSUE TITLE
KRB5_TRACE is set but not creating logs

### ISSUE THREAD

**Issue by john-tipper** [pythongssapi/python-gssapi#332]
### KRB5_TRACE does not create logs

I am trying to generate debug logs of a Flask app that uses Kerberos authentication by setting the environmental variable `KRB5_TRACE=/dev/stdout` but no logs are being generated. When I run `kinit` with that variable set I can see logs generated, so I know that my version of Kerberos does support this trace logging.

Is this by design (perhaps because the library is creating a secure context - I can see in the docs for [`krb5_init_secure_context()`](https://web.mit.edu/tsitkova/www/build/krb_appldev/refs/api/krb5_init_secure_context.html#krb5_init_secure_context) that environmental variables are ignored), or am I doing something wrong or is this a bug?

### How do we reproduce?

I am using the Kerberos wrapper function here and the example Flask app here: https://github.com/pythongssapi/python-gssapi/issues/164#issuecomment-509978190

### Component versions (python-gssapi, Kerberos, OS / distro, etc.)

python-gssapi 1.8.3
Kerberos 1.20.1
Amazon Linux 2

**Comment by john-tipper** [comment]
Thanks for the very prompt response, really much appreciated. Is there a way of determining whether I have MIT or Heimdal Kerberos installed please? I'm using the `krb5-devel` and `krb5-libs` RPMs from the amzn2-core repo but I don't know what implementation they represent - I'd like to be able to rule out the use of Heimdal as being the cause.

**Comment by jborean93** [comment]
You will have MIT krb5 with those package names. In any case `krb5-config --version` will show `Kerberos 5 release ...` for MIT and for Heimdal includes `Heimdal` in the output.

**Comment by john-tipper** [comment]
You’re right, sorry for the noise. The lack of logs was due to a Kerberos error with an incorrectly created keytab which was taking place before the logs started.
