### ISSUE TITLE
Implement RFC 4178 (SPNEGO) related extensions

### ISSUE THREAD

**Issue by DirectXMan12** [pythongssapi/python-gssapi#50]
RFC 4178 contains two methods for use with SPENGO: 
- gss_set_neg_mechs
- gss_get_neg_mechs (not implemented in MIT krb5)

These are useful to constrain the mechanisms that SPENGO can use

**Comment by optiz0r** [comment]
The code in #176 seems to work for me, it would be useful if this could be published as a new release :)

**Comment by frozencemetery** [comment]
Thanks for the feedback @optiz0r!  I'm waiting on Windows support (#177) which should merge soon, and then I'll cut a release.

(Closing ticket because it should have been closed with the merge of #176.)
