### ISSUE TITLE
Implement krb5-specific extensions

### ISSUE THREAD

**Issue by frozencemetery** [pythongssapi/python-gssapi#75]
These extensions are useful as a stopgap for applications looking to move from bindings to libkrb5 to our bindings to GSSAPI, especially `gss_krb5_ccache_name()`.

**Comment by frozencemetery** [comment]
For ease of reference, we are talking about (from gssapi_krb5.h):

- GSS_KRB5_NT_PRINCIPAL_NAME
- gss_krb5_ccache_name
- gss_krb5_copy_ccache
- gss_krb5_get_tkt_flags
- gss_krb5_set_allowable_enctypes

These are more niche:

- gss_krb5_export_lucid_sec_context
- gss_krb5_free_lucid_sec_context
- gsskrb5_extract_authz_data_from_sec_context
- gsskrb5_extract_authtime_from_sec_context

The following functionality is also available through the cred_store API
extensions so we may elect not to implement them at all:

- gss_krb5_set_cred_rcache
- gss_krb5_import_cred

**Comment by krizex** [comment]
I am also looking forward to the implementation of `gss_krb5_set_allowable_enctypes` which could help me get rid of the krb5.conf when using this library.

**Comment by jborean93** [comment]
https://github.com/pythongssapi/python-gssapi/pull/261 implements the following:

* GSS_KRB5_NT_PRINCIPAL_NAME
* gss_krb5_ccache_name
* gss_krb5_get_tkt_flags
* gss_krb5_set_allowable_enctypes
* gss_krb5_export_lucid_sec_context
* gss_krb5_free_lucid_sec_context
* gsskrb5_extract_authz_data_from_sec_context
* gsskrb5_extract_authtime_from_sec_context
* gss_krb5_import_cred
  * There is a note about this being available through the cred_store API. Unfortunately Heimdal did not implement `gss_acquire_cred_from` making this one way of importing a CCACHE for Heimdal on older versions - important for a use case I have

I didn't implement the following:

* gss_krb5_set_cred_rcache
    * Not present on Heimdal - seems quite limited to just implement for one
* gss_krb5_copy_ccache
    * It is marked as deprecated on macOS Heimdal implementation (not Heimdal itself)
    * It will compile but it does emit a warning and honestly just seems more trouble than it's worth
