### ISSUE TITLE
Token size specification

### ISSUE THREAD

**Issue by lambda-voodoo** [pythongssapi/python-gssapi#94]
When performing a negociation step such as shown in the code proposed in the documentation, it is not specified what size the client and the service should expect for an incoming token.

**Comment by DirectXMan12** [comment]
Can you clarify what your issue is here?.  Applications making use of GSSAPI are expected to define a protocol for transmitting the token that includes details like how much the other end of the connection needs to read to obtain the whole token.

**Comment by lambda-voodoo** [comment]
I could send the token along with its size computed on the fly of course but I was wondering if the token size is fixed or, at least, bounded.

**Comment by simo5** [comment]
It is mechanism specific and there is no fixed size.

**Comment by lambda-voodoo** [comment]
Thank you
