### ISSUE TITLE
`SecurityContext#delegated_creds` should be a property with documentation

### ISSUE THREAD

**Issue by DirectXMan12** [pythongssapi/python-gssapi#95]
Currently, `SecurityContext#delegated_creds` is just a normal instance attribute of `SecurityContext`, which means that it can be accidentally overwritten, and it does not show up in the documentation.  This should be fixed.

**Comment by simo5** [comment]
I think it should be possible to drop the delegated credentials esp if we allow to pickle the whole security context and then restore it.
Someone may want to pass around a security context but not transfer any delegated credentials to a lower priviliged process as dellegated credentials may include a delegated tgt.

**Comment by DirectXMan12** [comment]
Pickling the `SecurityContext` uses a special pickle process that doesn't actually pickle the object -- it just uses `export_sec_context()` (so the unpickling process just reconstitutes the `SecurityContext` using `import_sec_context()`).

**Comment by simo5** [comment]
This means delegated credentials get lost in the process.
On the one hand I think this is more secure, OTOH it may come as a suprise to the suer and should be carefully documented.

**Comment by DirectXMan12** [comment]
Yeah.  The only reason delegated creds are stored as a field is so that the "step" method can return only a token.  It should definitely be documented, though
